"""Seal 展示元数据。保留上游 Skill ID；网页与手册共享此表。"""

# ID -> (中文名称, 一句话用途)。实际流程和约束以对应 CAPABILITY.md 为准。
SKILL_LABELS = {
    "seal-xhs-public-research": ("小红书公开数据研究", "通过核验的 RedFox 接口研究公开账号、笔记、评论与热点数据。"),
    "ai-image-gen": ("AI 图片生成", "根据提示词生成图片，支持已配置的图片服务。"),
    "ai-music": ("AI 音乐创作", "生成适合内容主题与情绪的音乐素材。"),
    "ai-video-gen": ("AI 视频生成", "将文字或图片交给已配置的视频模型生成视频。"),
    "asset-manager": ("素材管理", "整理、检索与管理内容生产所需素材。"),
    "audio-denoise": ("音频降噪", "减少录音中的背景噪声，改善听感。"),
    "audio-editing": ("音频剪辑", "裁切、拼接与调整音频素材。"),
    "audio-mix": ("音轨混音", "混合人声、音乐和音效，调整音量层次。"),
    "audio-visualizer": ("音乐可视化", "把音频节奏转成可视化视频画面。"),
    "auto-short-video": ("短视频自动制作", "串联脚本、素材、配音与剪辑生成短视频。"),
    "auto-subtitle": ("自动字幕", "识别语音并生成带时间轴的字幕。"),
    "batch-process": ("批量处理", "按统一规格批量处理内容与媒体文件。"),
    "beat-sync-video": ("节奏卡点视频", "根据音乐节拍安排镜头切换与画面节奏。"),
    "card-design": ("通用卡片设计", "将结构化内容排成可发布的视觉卡片。"),
    "card-quote": ("金句卡片", "把短句与观点制作成简洁的金句卡片。"),
    "card-xiaohongshu": ("小红书图文卡片", "制作适合小红书阅读的多页图文卡片。"),
    "chart-visualization": ("数据图表", "根据真实数据生成清晰的可视化图表。"),
    "clipify": ("长视频拆条", "从长视频提取适合独立传播的短片段。"),
    "comparison-card": ("对比卡片", "用并列结构呈现产品、方案或观点差异。"),
    "copywriting": ("营销文案", "围绕受众、卖点和目标撰写营销文案。"),
    "data-report": ("数据报告", "整理数据与发现，输出可阅读的分析报告。"),
    "doc-convert": ("文档格式转换", "在支持的文档格式间转换内容。"),
    "ecom-details-image": ("电商详情配图", "围绕商品卖点制作营销图与详情页配图。"),
    "green-screen": ("绿幕抠像", "移除绿幕背景并合成新的画面背景。"),
    "image-editing": ("图片编辑", "裁剪、调整与组合已有图片素材。"),
    "image-enhance": ("图片画质增强", "改善图片清晰度、尺寸与视觉质量。"),
    "infographic": ("信息图设计", "将知识、流程与数据组织为信息图。"),
    "meme-generator": ("表情梗图", "结合图片与短句制作传播型梗图。"),
    "mindmap": ("思维导图", "将主题与层级关系整理成思维导图。"),
    "multi-voice-dubbing": ("多角色配音", "为不同角色分配声音并合成对话音轨。"),
    "novel-writer": ("小说创作", "规划人物、情节与章节，创作小说文本。"),
    "paper-explainer": ("论文解读", "提炼论文问题、方法、结果与局限。"),
    "post-formatter": ("社媒排版", "按目标平台整理文案段落与发布格式。"),
    "poster-hero": ("主视觉海报", "围绕核心信息设计活动或内容主视觉。"),
    "remove-bg": ("图片去背景", "分离图片主体，生成透明背景素材。"),
    "roi-calculator": ("投入产出测算", "根据成本和收益数据测算投入产出。"),
    "short-drama": ("AI 短剧制作", "串联剧情、分镜、角色画面与音视频制作。"),
    "skill-account-diagnosis": ("账号运营诊断", "结合账号数据找出增长问题与改进重点。"),
    "skill-algorithm-updates": ("平台规则追踪", "跟踪平台算法与规则变化，评估运营影响。"),
    "skill-article-outline": ("文章大纲", "按主题、受众与论点组织文章结构。"),
    "skill-audience-profiler": ("受众画像分析", "提炼目标受众的需求、兴趣与行为特征。"),
    "skill-bilibili-upload": ("哔哩哔哩投稿", "检查视频与投稿信息，经确认后提交 B 站。"),
    "skill-brand-onboarding": ("品牌信息建档", "梳理品牌定位、产品信息与内容要求。"),
    "skill-campaign-planner": ("营销活动策划", "规划活动目标、内容节奏与执行安排。"),
    "skill-carousel-planner": ("多页图文策划", "安排轮播图文的页序、信息量与阅读节奏。"),
    "skill-channels-upload": ("微信视频号发布", "准备视频号投稿内容，经确认后发布。"),
    "skill-collab-proposal": ("合作提案", "为品牌与创作者合作整理提案和交付范围。"),
    "skill-comment-insights": ("评论洞察", "从评论中提炼问题、需求与内容机会。"),
    "skill-community-ops": ("社群运营", "规划社群互动、用户维护与活动内容。"),
    "skill-competitor-analysis": ("竞品分析", "比较竞品定位、内容策略与表现。"),
    "skill-content-calendar": ("内容排期规划", "把选题与生产任务安排到内容日历。"),
    "skill-content-calendar-log": ("内容日历记录", "记录与维护内容排期和执行状态。"),
    "skill-content-gap-analysis": ("内容机会分析", "识别现有内容与受众需求之间的缺口。"),
    "skill-content-matrix": ("内容矩阵设计", "组织主题、形式与平台的内容组合。"),
    "skill-content-postmortem": ("单篇内容复盘", "回顾内容表现，归纳有效做法与改进项。"),
    "skill-content-repurposing": ("内容二次创作", "将已有内容改编为新的形式或平台版本。"),
    "skill-content-strategy": ("内容策略规划", "围绕运营目标制定内容方向与执行策略。"),
    "skill-cross-platform-diff": ("跨平台差异分析", "比较各平台规范与受众，提出适配建议。"),
    "skill-cross-platform-publish": ("多平台发布编排", "统筹平台版本与发布步骤，逐项留痕。"),
    "skill-data-tracker": ("运营数据追踪", "记录关键运营指标并观察变化。"),
    "skill-douyin-upload": ("抖音视频发布", "准备抖音视频与投稿信息，经确认后发布。"),
    "skill-event-calendar": ("节日活动日历", "查询与整理节日、大促及平台活动节点。"),
    "skill-hook-generator": ("开场吸引力设计", "为标题与开头设计吸引受众的表达。"),
    "skill-kuaishou-upload": ("快手视频发布", "准备快手视频与投稿信息，经确认后发布。"),
    "skill-livestream": ("直播策划", "设计直播主题、流程、话术与互动环节。"),
    "skill-my-account": ("我的账号信息", "读取已登录账号的身份与可用运营信息。"),
    "skill-news-intelligence": ("行业资讯洞察", "收集行业资讯，提炼相关趋势与内容机会。"),
    "skill-persona-check": ("人设一致性检查", "检查内容与账号定位、受众和表达是否一致。"),
    "skill-positioning-analysis": ("账号定位分析", "分析赛道、差异化优势与账号定位。"),
    "skill-post-scorer": ("内容潜力评分", "从内容结构与传播要素评估发布潜力。"),
    "skill-profile-builder": ("运营画像构建", "根据可用账号证据生成运营画像。"),
    "skill-profile-manager": ("运营画像管理", "维护账号定位、风格、偏好与经验记录。"),
    "skill-publish-analytics": ("发布效果分析", "汇总已发布内容的表现与效果指标。"),
    "skill-publish-checklist": ("发布前检查", "核对素材、文案、平台规格与发布条件。"),
    "skill-publish-log": ("发布记录", "记录发布结果、链接与关联内容信息。"),
    "skill-publish-notify": ("发布结果通知", "按授权将发布结果发送到配置的通知渠道。"),
    "skill-publish-scheduler": ("定时发布安排", "准备发布排期；Codex 模式由桌面自动化承接。"),
    "skill-quality-gate": ("内容质量检查", "检查产物完整性、内容质量与交付规格。"),
    "skill-risk-scanner": ("内容风险扫描", "识别文案中的敏感信息与平台合规风险。"),
    "skill-rss-aggregator": ("订阅资讯聚合", "聚合 RSS 订阅内容，整理选题线索。"),
    "skill-seo-quality": ("搜索优化检查", "检查内容的搜索可发现性与基础质量。"),
    "skill-short-link": ("短链接管理", "生成或管理支持追踪的短链接。"),
    "skill-social-performance-review": ("社媒运营复盘", "综合多项数据评估阶段运营表现。"),
    "skill-strategy-advisor": ("运营策略顾问", "根据账号现状与目标提出行动建议。"),
    "skill-topic-evaluator": ("选题价值评估", "评估选题相关性、可执行性与传播机会。"),
    "skill-trend-rider": ("热点借势策划", "将热点与账号定位结合，形成创作切入点。"),
    "skill-trending-topics": ("热点发现", "获取平台热点榜单与选题线索。"),
    "skill-ugc-discovery": ("用户内容发现", "发现可参考的用户创作与真实需求线索。"),
    "skill-voice-builder": ("品牌语气构建", "提炼品牌或账号的语言风格与表达规范。"),
    "skill-wechat-publisher": ("微信公众号发布", "整理公众号文章与素材，按授权提交。"),
    "skill-xhs-analyzer": ("小红书账号分析", "通过可用数据分析小红书账号与笔记表现。"),
    "skill-xhs-comment-reply": ("小红书评论回复", "读取评论、拟定回复，经确认后执行互动。"),
    "skill-xhs-publisher": ("小红书笔记发布", "预检图文或视频，使用本地登录态完成发布。"),
    "skill-zhihu-answer": ("知乎回答创作", "围绕问题组织有依据、有结构的回答。"),
    "skill-zhihu-publisher": ("知乎内容发布", "整理知乎回答或文章，按授权提交发布。"),
    "slideshow-video": ("图集转视频", "将图片按顺序合成带转场的展示视频。"),
    "social-content": ("社媒内容创作", "为目标社交平台撰写内容与互动文案。"),
    "style-transfer": ("内容风格迁移", "参照目标风格调整内容的表达方式。"),
    "subtitle-translate": ("字幕翻译", "翻译字幕并保留时间轴与文件结构。"),
    "template-library": ("创作模板库", "检索、复用与管理内容创作模板。"),
    "text-condenser": ("文本精简", "压缩冗长文本，保留核心信息与逻辑。"),
    "text-polisher": ("文本润色", "改善语言流畅度、结构与表达准确性。"),
    "tts-voiceover": ("文字配音", "将文本转换为旁白或口播音频。"),
    "video-chapters": ("视频章节标记", "按视频内容划分章节并生成时间标记。"),
    "video-editing": ("视频剪辑", "裁切、拼接、调整和处理视频素材。"),
    "video-highlights": ("视频高光提取", "识别并提取视频中的重点与精彩片段。"),
    "video-intro-outro": ("视频片头片尾", "制作或添加统一的片头与片尾。"),
    "video-reframe": ("视频画幅适配", "调整视频画幅以适配不同平台尺寸。"),
    "video-script": ("视频脚本创作", "编写视频口播、画面说明与镜头脚本。"),
    "video-strategy": ("视频内容策略", "规划视频选题、形式与系列化方向。"),
    "video-to-article": ("视频转文章", "从视频信息整理可独立阅读的文章。"),
    "voice-clone": ("声音克隆", "在获得声音授权后调用支持的克隆服务。"),
    "xhs-note-creator": ("小红书笔记创作", "围绕主题制作标题、正文、话题与配图方案。"),
}


def skill_label(name: str) -> tuple[str, str]:
    # 新增上游 Skill 时显式提示待维护，不用机械翻译拼接冒充中文名。
    return SKILL_LABELS.get(name, (name, "新增技能，中文说明待补充。"))
